version: "3"
services:
  db:
    image: ankane/pgvector
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    networks:
      - tota
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tota_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - tota

  mail:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "1025:1025"
    environment:
      MP_UI_BIND_ADDR: :9000
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pgdata:
networks:
  tota:
