/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/zoeken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Voor een bedrijf zoeken naar basisinformatie.
         * @description Er wordt max. 1000 resultaten getoond.
         */
        get: operations["getResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Binnenlands of buitenlands adres */
        Adres: {
            binnenlandsAdres?: components["schemas"]["BinnenlandsAdres"];
            buitenlandsAdres?: components["schemas"]["BuitenlandsAdres"];
        };
        /**
         * @description Bezoekadres of postadres
         * @enum {string}
         */
        AdresType: "bezoekadres" | "postadres";
        BinnenlandsAdres: {
            type?: components["schemas"]["AdresType"];
            straatnaam?: string;
            /** Format: int32 */
            huisnummer?: number;
            huisletter?: string;
            /**
             * Format: int32
             * @description Postbusnummer wordt alleen getoond indien het een postadres betreft
             */
            postbusnummer?: number;
            postcode?: string;
            plaats?: string;
        };
        BuitenlandsAdres: {
            type?: components["schemas"]["AdresType"];
            /**
             * @description Het straat/huisnummer is een combinatie van de straat en huisnummer
             * @example 53 Rue de Tilsitt
             */
            straatHuisnummer?: string;
            /**
             * @description De postcode/woonplaats is de combinatie van een eventuele postcode en woonplaats
             * @example X-13501 Parijs
             */
            postcodeWoonplaats?: string;
            /**
             * @description De naam van het land waar het adres bevindt
             * @example Frankrijk
             */
            land?: string;
        };
        Links: {
            [key: string]: components["schemas"]["Link"];
        };
        Resultaat: {
            /**
             * Format: int32
             * @description Geeft aan op welke pagina je bent. Start vanaf pagina 1
             */
            pagina?: number;
            /**
             * Format: int32
             * @description Geeft het aantal zoek resultaten per pagina weer
             */
            resultatenPerPagina?: number;
            /**
             * Format: int32
             * @description Totaal aantal zoekresultaten gevonden. De API Zoeken toont max. 1000 resultaten.
             */
            totaal?: number;
            /** @description Link naar de vorige pagina indien beschikbaar */
            vorige?: string;
            /** @description Link naar de volgende pagina indien beschikbaar */
            volgende?: string;
            resultaten?: components["schemas"]["ResultaatItem"][];
            _links?: components["schemas"]["Links"];
        };
        ResultaatItem: {
            /** @description Nederlands Kamer van Koophandel nummer dat bestaat uit 8 cijfers */
            kvkNummer?: string;
            /** @description Rechtspersonen Samenwerkingsverbanden Informatie Nummer dat bestaat uit 9 cijfers */
            rsin?: string;
            /** @description Vestigingsnummer dat bestaat uit 12 cijfers */
            vestigingsnummer?: string;
            /** @description De naam waaronder een vestiging of rechtspersoon handelt */
            naam?: string;
            adres?: components["schemas"]["Adres"];
            /** @description hoofdvestiging/nevenvestiging/rechtspersoon */
            type?: string;
            /** @description Indicatie of inschrijving actief is */
            actief?: string;
            /** @description Bevat de vervallen naam waaronder een vestiging of rechtspersoon heeft gehandeld */
            vervallenNaam?: string;
            _links?: components["schemas"]["Links"];
        };
        Link: {
            href?: string;
            title?: string;
        };
        Error: {
            fout?: components["schemas"]["Fout"][];
        };
        Fout: {
            /** @description Foutcode */
            code?: string;
            /** @description Omschrijving van de foutmelding */
            omschrijving?: string;
        };
    };
    responses: {
        /** @description Een opgegeven parameter is niet valide */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
                "application/hal+json": components["schemas"]["Error"];
            };
        };
        /** @description Geen of onjuiste apikey aangeleverd */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
                "application/hal+json": components["schemas"]["Error"];
            };
        };
        /** @description Niet geautoriseerd voor deze operatie */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
                "application/hal+json": components["schemas"]["Error"];
            };
        };
        /** @description Er zijn geen resultaten gevonden aan de hand van de opgegeven parameter(s) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
                "application/hal+json": components["schemas"]["Error"];
            };
        };
        /** @description Opgegeven Accept header wordt niet ondersteund */
        NotAcceptable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
                "application/hal+json": components["schemas"]["Error"];
            };
        };
        /** @description Er is een interne fout opgetreden */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
                "application/hal+json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        api_version: string;
        warning: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getResults: {
        parameters: {
            query?: {
                /**
                 * @description Nederlands Kamer van Koophandel nummer dat bestaat uit 8 cijfers
                 * @example 59581883
                 */
                kvkNummer?: string;
                /**
                 * @description Rechtspersonen Samenwerkingsverbanden Informatie Nummer dat bestaat uit 9 cijfers
                 * @example 823807071
                 */
                rsin?: string;
                /**
                 * @description Vestigingsnummer dat bestaat uit 12 cijfers
                 * @example 000015063097
                 */
                vestigingsnummer?: string;
                /**
                 * @description De naam waaronder een vestiging of rechtspersoon handelt
                 * @example Kamer van Koophandel
                 */
                naam?: string;
                /** @example St.-Jacobsstraat */
                straatnaam?: string;
                /** @example Utrecht */
                plaats?: string;
                /**
                 * @description Mag alleen in combinatie met huisnummer of postbusnummer gezocht worden
                 * @example 3511BT
                 */
                postcode?: string;
                /**
                 * @description Mag alleen in combinatie met postcode gezocht worden
                 * @example 300
                 */
                huisnummer?: number;
                /**
                 * @description Optioneel. Alleen in combinatie met huisnummer
                 * @example D
                 */
                huisletter?: string;
                /**
                 * @description Mag alleen in combinatie met postcode gezocht worden
                 * @example 9292
                 */
                postbusnummer?: number;
                /**
                 * @description Filter op type: hoofdvestiging, nevenvestiging en/of rechtspersoon
                 * @example hoofdvestiging
                 */
                type?: ("hoofdvestiging" | "nevenvestiging" | "rechtspersoon")[];
                /**
                 * @description Inclusief inactieve registraties
                 * @example true
                 */
                inclusiefInactieveRegistraties?: boolean;
                /** @description Paginanummer, minimaal 1 en maximaal 1000 */
                pagina?: number;
                /** @description Kies het aantal resultaten per pagina, minimaal 1 en maximaal 100 */
                resultatenPerPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "api-version": components["headers"]["api_version"];
                    warning: components["headers"]["warning"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resultaat"];
                    "application/hal+json": components["schemas"]["Resultaat"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            406: components["responses"]["NotAcceptable"];
            500: components["responses"]["InternalServerError"];
            /** @description Er is een onverwachte fout opgetreden */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                    "application/hal+json": components["schemas"]["Error"];
                };
            };
        };
    };
}
